[package]
name = "netnfi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysfs-class = "0.1.3"
ipnetwork = "0.20"
libc = "0.2"
clap = "2"
get_if_addrs = "0.5"
